apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mechanic.fullname" . }}
  labels:
    {{- include "mechanic.labels" . | nindent 4 }}
immutable: false
data:
  OPENAI_BASE_URL: "http://{{ .Release.Name }}-openai-responses-api-service:8321/v1"
  OPENAI_API_KEY: "no_key_needed"
  MODEL: "vllm-inference/gemma-4"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://eclipse.home.glroland.com:4317"
  OTEL_EXPORTER_OTLP_HEADERS: ""
  MLFLOW_TRACKING_URI: "https://rh-ai.apps.ocp.home.glroland.com/mlflow"
  MLFLOW_TRACKING_AUTH: "kubernetes-namespaced"
  MLFLOW_EXPERIMENT_ID: "mechanic-chatbot"
