apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mechanic.fullname" . }}
  labels:
    {{- include "mechanic.labels" . | nindent 4 }}
immutable: false
data:
  OPENAI_BASE_URL: "http://{{ .Release.Name }}-openai-responses-api-service:8321/v1"
  OPENAI_API_KEY: "no_key_needed"
  MODEL: "vllm-inference/gemma-4"
  MLFLOW_TRACKING_URI: "https://rh-ai.apps.ocp.home.glroland.com/mlflow"
  MLFLOW_TRACKING_AUTH: "kubernetes-namespaced"
  MLFLOW_EXPERIMENT_ID: "3"
  MLFLOW_EXPERIMENT_NAME: "mechanic-chatbot-v2"
