apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mechanic.fullname" . }}
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Release.Name }}-chatbot"}]'
  labels:
    app.kubernetes.io/part-of: "{{ .Release.Name }}-mechanic"
    {{- include "mechanic.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mechanic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mechanic.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.image.usePullSecret }}
      imagePullSecrets:
      - name: mechanic-pull-secret
      {{- end }}
      serviceAccountName: {{ include "mechanic.fullname" . }}-sa
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.repository }}{{ .Values.image.name }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.image.port }}
          env:
            - name: OPENAI_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mechanic.fullname" . }}
                  key: OPENAI_BASE_URL
            - name: OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mechanic.fullname" . }}
                  key: OPENAI_API_KEY
            - name: MODEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mechanic.fullname" . }}
                  key: MODEL
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mechanic.fullname" . }}
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mechanic.fullname" . }}
                  key: MLFLOW_TRACKING_URI
            - name: MLFLOW_TRACKING_AUTH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mechanic.fullname" . }}
                  key: MLFLOW_TRACKING_AUTH
            - name: MLFLOW_WORKSPACE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mechanic.fullname" . }}
                  key: MLFLOW_WORKSPACE
            - name: MLFLOW_EXPERIMENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mechanic.fullname" . }}
                  key: MLFLOW_EXPERIMENT_ID
            - name: MLFLOW_TRACKING_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mechanic.fullname" . }}
                  key: MLFLOW_TRACKING_TOKEN
            - name: SET_TOKEN_FROM_FILE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mechanic.fullname" . }}
                  key: SET_TOKEN_FROM_FILE
            - name: MLFLOW_TRACKING_HEADERS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mechanic.fullname" . }}
                  key: MLFLOW_TRACKING_HEADERS
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mechanic.fullname" . }}
                  key: OTEL_EXPORTER_OTLP_HEADERS
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
