apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mechanic.fullname" . }}-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5ob21lLmdscm9sYW5kLmNvbSI6IHsKICAgICAgImF1dGgiOiAiWVdrdGNISnZaSFZqZEMxallYUmhiRzluSzI5amNEUTZWRE5TUVZBM1ZGSXlSRFJXV0ZoWldFTXlRbEpEV2tsRlRrZENTVE5RTVVkSE1GSldWRXhaT0ZwRlF6a3lOekExTVRWQlNFUlhNbE5HVWtOSlMwaEZPQT09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson