apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mechanic.fullname" . }}-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mechanic_lls_storage
    server: rack.home.glroland.com
  storageClassName: static-nfs-storage-class
