apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-mechanic-sa-anyuid-rb
  namespace: mechanic
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-mechanic-sa
  namespace: mechanic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
