kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "mechanic.serviceAccountName" . }}-sa-mlflow-role-binding
subjects:
  - kind: ServiceAccount
    name:  {{ include "mechanic.serviceAccountName" . }}-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mlflow-operator-mlflow-integration
