global:

  image:
    repository: registry.home.glroland.com/mechanic/
    tag: 33 # last success - 32
    pullPolicy: IfNotPresent
    usePullSecret: true

  podAnnotations: {}

  podSecurityContext: {}

  useServiceAccount: false

  securityContext: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}
